spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_dev
    username: stock_dev_user
    password: dev
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true